# Generated by Django 5.2.3 on 2025-06-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('yearfunda', models.IntegerField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imgempresa')),
            ],
        ),
    ]
