# Generated by Django 5.2.3 on 2025-06-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_direccion_alter_empresa_mision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='mision',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='vision',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
