# Generated by Django 5.2.3 on 2025-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('mision', models.CharField(max_length=300, verbose_name='Misión')),
                ('vision', models.CharField(max_length=300, verbose_name='Visión')),
                ('yearfunda', models.DateField(verbose_name='Año de Fundación')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('imagen', models.ImageField(upload_to='imgempresa', verbose_name='Imagen')),
            ],
        ),
    ]
