# Generated by Django 5.2.3 on 2025-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('codigo_empleado', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('imagen', models.ImageField(upload_to='imgtrabajadores')),
            ],
        ),
    ]
